#!/usr/bin/env bash
# set up load balancer
#sudo apt-get -y install software-properties-common
#sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
#sudo apt-get -y update
#sudo apt-get -y install haproxy

#sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
#sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 525-web-01 35.231.216.93:80 check\n\tserver 525-web-02 35.196.0.213:80 check\n' /etc/haproxy/haproxy.cfg
#sudo service haproxy restart
# -----------------------------------------------------------------------------------------------------------------
#!/usr/bin/env bash
# Installs, configures, and starts the load balancer
apt-get update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y install haproxy
# the load balancer's configuration
DOMAIN_NAME='mgidey.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG=\
"
#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
        balance roundrobin
        server 101469-web-01 34.207.121.86:80 check
        server 101469-web-02 100.26.169.172:80 check

frontend $DOMAIN_NAME-frontend
        bind *:80
        mode http

        default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"

[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < $CONFIG_FILE)

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
        sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
        echo 'ENABLED=1' >> $INIT_FILE
fi

if [ "$CONFIG_WORDS" -eq 0 ]; then
        echo -e "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
else
        start_tkn="#--$DOMAIN_NAME-params-begin--"
        end_tkn="#--$DOMAIN_NAME-params-end--"
        a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
        b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
        a=$((a - 1))
        b=$((b + 1))
        sed -i "$a,$b"d "$CONFIG_FILE"
        echo -en "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
        service haproxy start
else
        service haproxy restart
fi
